// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if Supabase URL is valid (not a placeholder)
const isValidSupabaseUrl = SUPABASE_URL && SUPABASE_URL.includes('supabase.co') && !SUPABASE_URL.includes('wuewukvvnvnkvzyvksxq');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isValidSupabaseUrl
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : null;

// Export a flag to check if Supabase is available
export const isSupabaseAvailable = isValidSupabaseUrl && !!supabase;